#!/usr/bin/env python

from velocity_publisher import computation

import rospy
from geometry_msgs.msg import Twist


def move_robot():
    """Function that builds and publishes messages to the cmd_vel topic"""

    # cmd_vel_publisher is the name of the node
    # anonymous=True will give a unique id to the node
    # anonymous=True allows you to create multiple instances of this node
    rospy.init_node("cmd_vel_publisher", anonymous=True)

    # Create a publisher
    pub = rospy.Publisher("cmd_vel", Twist, queue_size=10)
    # Create a message of type Twist
    message = Twist()
    # Build your message
    message.linear.x = 2   # message.linear.y=0 and message.linear.z=0
    message.angular.z = 1  # message.angular.x=0 and message.angular.y=0 by default
    # message.angular.z = computation.generate_random()
    # How often to publish the message
    rate = rospy.Rate(1)

    # Publish messages in a loop (until will we do Ctrl-C)
    while not rospy.is_shutdown():
        pub.publish(message)
        rate.sleep()


if __name__ == "__main__":
    move_robot()
